# Generated by Django 4.2.30 on 2026-09-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='currency_symbol',
        ),
        migrations.AddField(
            model_name='country',
            name='emblem',
            field=models.CharField(blank=True, help_text='e.g. 🇮🇳, 🇦🇪', max_length=10, null=True),
        ),
    ]
