# Generated by Django 4.2.30 on 2026-09-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_remove_country_currency_symbol_country_emblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='dial_code',
            field=models.CharField(blank=True, help_text='e.g. +91, +971, +44', max_length=10, null=True),
        ),
    ]
